# Generated by Django 3.2.4 on 2021-06-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InformationBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Название блока')),
                ('description', models.TextField(verbose_name='Описание блока')),
                ('views', models.IntegerField(default=0, verbose_name='Количество посещений')),
            ],
            options={
                'verbose_name': 'Блок',
                'verbose_name_plural': 'Блоки',
                'ordering': ['-name'],
            },
        ),
    ]
