# Generated by Django 3.2.4 on 2021-06-27 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('telegram_username', models.CharField(default='', max_length=100, verbose_name='Username')),
                ('message', models.TextField(max_length=500, verbose_name='Текст сообщения')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='AdminTelegramId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=15, verbose_name='Телеграм ID')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_id', to='master.master', verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'Телеграм ID',
                'verbose_name_plural': 'Телеграм ID',
            },
        ),
    ]
