# Generated by Django 3.2.4 on 2021-06-27 10:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя мастера')),
                ('image', models.ImageField(upload_to='masters/', verbose_name='Изображение мастера')),
                ('about_master', models.TextField(max_length=180, verbose_name='Информация о мастере')),
                ('vk', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на ВК')),
                ('instagram', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на Instagram')),
                ('telegram', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на Telegram')),
            ],
            options={
                'verbose_name': 'Мастер',
                'verbose_name_plural': 'Мастера',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RecordToMasterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('telegram_username', models.CharField(default='', max_length=100, verbose_name='Username')),
                ('message', models.TextField(max_length=500, verbose_name='Текст сообщения')),
                ('master', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='master_to_record', to='master.master', verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='MasterSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('value', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Значение (%)')),
                ('master', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='master_skills', to='master.master', verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'Умение мастера',
                'verbose_name_plural': 'Умения мастера',
                'ordering': ['name'],
            },
        ),
    ]
